# Generated by Django 5.0.3 on 2025-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
                ('guardian_email', models.EmailField(max_length=100)),
                ('guardian_first_name', models.CharField(default='missing', max_length=50)),
                ('guardian_last_name', models.CharField(default='missing', max_length=50)),
            ],
        ),
    ]
