# Generated by Django 5.0.3 on 2025-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
                ('learning_needs', models.TextField()),
                ('guardian_email', models.EmailField(max_length=100)),
                ('disability_status', models.CharField(blank=True, max_length=100, null=True)),
                ('support_level', models.CharField(choices=[('Quality Differentiated Teaching', 'Quality Differentiated Teaching'), ('Supplementary', 'Supplementary'), ('Substantial', 'Substantial'), ('Extensive', 'Extensive')], max_length=31)),
                ('funding_eligibility', models.BooleanField(default=False)),
            ],
        ),
    ]
