# Generated by Django 5.0.3 on 2025-05-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_first_name', models.CharField(blank=True, db_column='first_name')),
                ('_last_name', models.CharField(blank=True, db_column='last_name')),
                ('year_level', models.IntegerField(choices=[(0, 'Prep'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('student_email', models.EmailField(default='missing', max_length=100)),
                ('_disability_info', models.TextField(blank=True, db_column='disability_info')),
            ],
        ),
    ]
