# Generated by Django 5.0.3 on 2025-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='_first_name',
            field=models.CharField(blank=True, db_column='first_name'),
        ),
        migrations.AddField(
            model_name='student',
            name='_last_name',
            field=models.CharField(blank=True, db_column='last_name'),
        ),
    ]
