# Generated by Django 5.0.3 on 2025-04-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='disability_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='funding_eligibility',
        ),
        migrations.RemoveField(
            model_name='student',
            name='support_level',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_first_name',
            field=models.CharField(default='missing', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_last_name',
            field=models.CharField(default='missing', max_length=50),
        ),
    ]
