# Generated by Django 5.0.3 on 2025-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disability_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='missing', max_length=100),
        ),
    ]
