# Generated by Django 5.0.3 on 2025-05-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='missing', max_length=100, unique=True),
        ),
    ]
