# Generated by Django 5.0.3 on 2025-04-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_disability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='learning_needs',
        ),
    ]
