# Generated by Django 5.0.3 on 2025-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-pics/default.png', null=True, upload_to='profile-pics/'),
        ),
    ]
