# Generated by Django 5.0.3 on 2025-05-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
