# Generated by Django 5.0.3 on 2025-05-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCDreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('Approved', 'Approved'), ('NotStart', 'NotStart')], default='NotStarted', max_length=20)),
                ('disability_category', models.CharField(choices=[('Cognitive', 'Cognitive'), ('Physical', 'Physical'), ('Social/Emotional', 'Social/Emotional'), ('Sensory', 'Sensory')], default='None', max_length=20)),
                ('level_of_adjustment', models.CharField(choices=[('QDTP', 'QDTP'), ('Supplementary', 'Supplementary'), ('Substantial', 'Substantial'), ('Extensive', 'Extensive')], default='None', max_length=20)),
                ('evidence', models.FileField(upload_to='nccdreports/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='LessonEffectivenessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(auto_now_add=True)),
                ('was_effective', models.BooleanField()),
                ('feedback', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_records', to='nccdreports.nccdreport')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('progress_notes', models.TextField(blank=True)),
                ('parent_consulted', models.BooleanField(default=False)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='nccdreports/questionnaire_evidence/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='nccdreports.nccdreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
