# Generated by Django 5.0.3 on 2025-04-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCDreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InProgress', 'InProgress'), ('Approved', 'Approved'), ('NotStart', 'NotStart')], default='NotStarted', max_length=20)),
                ('has_diagonsed_disability', models.BooleanField(default=False)),
                ('disability_category', models.CharField(choices=[('Cognitive', 'Cognitive'), ('Physical', 'Physical'), ('Social/Emotional', 'Social/Emotional'), ('Sensory', 'Sensory')], default='None', max_length=20)),
                ('level_of_adjustment', models.CharField(choices=[('QDTP', 'QDTP'), ('Supplementary', 'Supplementary'), ('Substantial', 'Substantial'), ('Extensive', 'Extensive')], default='None', max_length=20)),
                ('evidence', models.FileField(upload_to='nccdreports/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
