# Generated by Django 5.0.3 on 2025-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccdreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccdreport',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nccdreport',
            name='has_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nccdreport',
            name='under_dda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nccdreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='nccdreports/'),
        ),
    ]
