# Generated by Django 5.0.3 on 2025-05-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccdreports', '0001_initial'),
        ('students', '0002_remove_student_first_name_remove_student_last_name_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoneffectivenessrecord',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('progress_notes', models.TextField(blank=True)),
                ('parent_consulted', models.BooleanField(default=False)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='nccdreports/questionnaire_evidence/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='nccdreports.nccdreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
