# Generated by Django 5.0.3 on 2025-05-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccdreports', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nccdreport',
            name='has_diagonsed_disability',
        ),
        migrations.AddField(
            model_name='lessoneffectivenessrecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
