# Generated by Django 5.0.3 on 2025-05-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccdreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccdreport',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nccdreport',
            name='under_dda',
            field=models.BooleanField(default=False),
        ),
    ]
