# Generated by Django 5.0.3 on 2025-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccdreports', '0002_nccdreport_additional_comments_nccdreport_under_dda'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccdreport',
            name='has_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nccdreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='nccdreports/'),
        ),
    ]
