# Generated by Django 5.0.3 on 2025-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0002_student_disability_info_student_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='students.student'),
        ),
    ]
