# Generated by Django 5.0.3 on 2025-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
