# Generated by Django 5.0.3 on 2025-05-13 06:34

import django.db.models.deletion
import django.utils.timezone
import unitplan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to=unitplan.models.unit_plan_file_path)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan', to='classes.classes')),
            ],
        ),
    ]
