# Generated by Django 5.2 on 2025-05-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="learning_materials/")),
                ("objective", models.TextField(blank=True, null=True)),
                ("ai_processed", models.BooleanField(default=False)),
                (
                    "class_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.classes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning material",
                "verbose_name_plural": "Learning materials",
            },
        ),
    ]
